# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [17]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import warnings

# Import API key
from api_keys import g_key

# Access maps with unique API key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [18]:
#load import weather data and make it into DataFrame
csv = "Output/weather_data.csv"
weather_data = pd.read_csv(csv)
weather_data.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Rikitea,-23.1203,-134.9692,25.63,72,100,3.12,PF,1619487006
1,Yellowknife,62.4560,-114.3525,-13.00,52,20,6.17,CA,1619486807
2,Aykhal,66.0000,111.5000,-10.54,89,99,6.39,RU,1619487006
3,Mulchén,-37.7167,-72.2333,10.54,70,3,1.62,CL,1619487006
4,Winston,28.0317,-82.0148,24.00,60,1,2.57,US,1619487006

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [19]:
# Access maps with unique API key
gmaps.configure(api_key=g_key)
# Store latitude and longitude in locations
locations = weather_data[["Lat", "Lng"]]
# defining weight for heatmap
humidity = weather_data["Humidity"]

In [20]:
# Plot Heatmap
humidity_heatmap = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)


# Add layer
humidity_heatmap.add_layer(heat_layer)

# Display figure
humidity_heatmap

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# the ideal weather conditions are:
#  A max temperature lower than 26 degrees celsius but higher than 21.
#  Wind speed less than 10 mph.
#  Zero cloudiness.
#  Humidity less than 85% 
#subset to include data points with only ideal conditions
weather_ideal = weather_data.loc[(weather_data["Max Temp"] <= 26) &
                                (weather_data["Max Temp"] >= 21) & 
                                (weather_data["Wind Speed"] <= 10) &
                                 (weather_data["Humidity"] <= 85) &
                                 (weather_data["Cloudiness"] == 0),:] 
#display ideal cities
weather_ideal

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
18,Belmonte,-15.8631,-38.8828,24.00,78,0,2.57,BR,1619487008
152,Adelaide,-34.9333,138.6000,21.67,52,0,3.60,AU,1619486972
178,Santiago,-33.4569,-70.6483,21.11,63,0,2.06,CL,1619487029
180,Carnarvon,-24.8667,113.6333,24.00,38,0,1.54,AU,1619487020
265,Tall Kayf,37.0833,41.0667,22.00,43,0,4.12,TR,1619487040
342,Aswān,24.0934,32.9070,23.13,29,0,5.64,EG,1619487050
394,Gunnedah,-30.9833,150.2500,21.67,59,0,0.45,AU,1619487057
433,Alice Springs,-23.7000,133.8833,23.33,26,0,7.72,AU,1619487008
567,Manta,-0.9500,-80.7333,25.00,83,0,3.09,EC,1619487078
587,Ibaté,-21.9547,-47.9967,21.00,83,0,3.60,BR,1619487081

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [11]:
#storing variable in to hotel_df
hotel_df = weather_ideal

#inserting new blank column
hotel_df["Hotel Name"] = ""

#clean output
warnings.filterwarnings('ignore')

#output
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
18,Belmonte,-15.8631,-38.8828,24.00,78,0,2.57,BR,1619487008,
152,Adelaide,-34.9333,138.6000,21.67,52,0,3.60,AU,1619486972,
178,Santiago,-33.4569,-70.6483,21.11,63,0,2.06,CL,1619487029,
180,Carnarvon,-24.8667,113.6333,24.00,38,0,1.54,AU,1619487020,
265,Tall Kayf,37.0833,41.0667,22.00,43,0,4.12,TR,1619487040,
342,Aswān,24.0934,32.9070,23.13,29,0,5.64,EG,1619487050,
394,Gunnedah,-30.9833,150.2500,21.67,59,0,0.45,AU,1619487057,
433,Alice Springs,-23.7000,133.8833,23.33,26,0,7.72,AU,1619487008,
567,Manta,-0.9500,-80.7333,25.00,83,0,3.09,EC,1619487078,
587,Ibaté,-21.9547,-47.9967,21.00,83,0,3.60,BR,1619487081,

In [7]:
# find hotels near ideal locations
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#setting up param dict for for loop
params = {
    "radius": 5000,
    "keyword": "hotel",
    "key": g_key,
}
print("Starting Search")
print('------------------------------------------------')
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():
    #assembling appropriate coordinates for params
    lat = row["Lat"]
    lng = row["Lng"]
    city = row["City"]
    params["location"] = f'{lat},{lng}'
    
    # assemble url and make API request
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    # error catch if there are no hotels in range or missing
    try:
        print(f"The first hotel result near {city} is: {results[0]['name']}.")
        print("------------------------------------------------")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']
    #what to output if there is an error    
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        print("------------------------------------------------")
print("Finished Search")
#clean output
warnings.filterwarnings('ignore')

Starting Search
------------------------------------------------
The first hotel result near Belmonte is: Pousada do Diogo.
------------------------------------------------
The first hotel result near Adelaide is: Crowne Plaza Adelaide.
------------------------------------------------
The first hotel result near Santiago is: Hotel Magnolia.
------------------------------------------------
The first hotel result near Carnarvon is: Hospitality Carnarvon.
------------------------------------------------
Missing field/result... skipping.
------------------------------------------------
The first hotel result near Aswān is: Sofitel Legend Old Cataract Aswan.
------------------------------------------------
The first hotel result near Gunnedah is: Mackellar Pet Friendly Motel Gunnedah.
------------------------------------------------
The first hotel result near Alice Springs is: DoubleTree by Hilton Hotel Alice Springs.
------------------------------------------------
The first hotel result near Manta is: Hotel Vistalmar.
------------------------------------------------
The first hotel result near Ibaté is: Hotel Veneza.
------------------------------------------------
Finished Search

In [8]:
hotel_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
18,Belmonte,-15.8631,-38.8828,24.00,78,0,2.57,BR,1619487008,Pousada do Diogo
152,Adelaide,-34.9333,138.6000,21.67,52,0,3.60,AU,1619486972,Crowne Plaza Adelaide
178,Santiago,-33.4569,-70.6483,21.11,63,0,2.06,CL,1619487029,Hotel Magnolia
180,Carnarvon,-24.8667,113.6333,24.00,38,0,1.54,AU,1619487020,Hospitality Carnarvon
265,Tall Kayf,37.0833,41.0667,22.00,43,0,4.12,TR,1619487040,

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
humidity_heatmap.add_layer(markers)

# Display figure
humidity_heatmap

Figure(layout=FigureLayout(height='420px'))